### ISSUE TITLE
Reassure procedure to measure trivial/non-trivial loops

### ISSUE THREAD

**Issue by mbecker12** [mbecker12/surface-rl-decoder#27]
#22 
#7 
Make sure that the implemented function check_final_state() in surface_code_util.py return the correct final_state and ground state boolean

**Comment by mbecker12** [comment]
a column full of X operators should perform a logical X operation -> change of logical state
what happens with a row full of X operators? is the logical qubit still in the ground state (but with errors)?
@mats-granath

**Comment by mbecker12** [comment]
Check function `check_final_state()` in `surface_code_util.py` for that

**Comment by mats-granath** [comment]
I will assume we're talking about the non-rotated code. And if you say a column of X gives a logical operator it means that the smooth edges are top and bottom. (I haven't checked the code if this is the case.) A row of X's (from rough to rough edge) has a syndrome. Then you cannot uniquely say that it is in one of the ground state sectors. It's a good question how one would treat this within our algorithm.  One way is to still evaluate the parity of X or Z on two edges, but I'm not sure this is the correct/best. I need to think about it.

**Comment by mats-granath** [comment]
My suggestion is to first check if there is a syndrome in the complete real error chain+correction. If there is, give negative reward based on the number of defects. If there is no syndrome look for non-trivial loops (i.e. in practice count parity of x or Z errors on two sides) and give negative reward for those. Not sure about the balance in negative reward, but I think we should only count as successful operation a complete recovery, i.e. no syndrome and no logical operators.

**Comment by mats-granath** [comment]
The function check_final_state looks fine, but after the perform_all_actions I think you should check that the syndrome is empty, and if not give reward based on that rather than on check_final_state.

**Comment by mbecker12** [comment]
![rotated_surface_code](https://user-images.githubusercontent.com/57626872/109010641-51956900-76b0-11eb-9456-d8e38ea6d81d.png)
Am I correct that the depicted concatenations of X operators along the red lines introduce a logical X operator? (looking at the rotated surface code)
![rotated_surface_code](https://user-images.githubusercontent.com/57626872/109010789-84d7f800-76b0-11eb-9dab-e8ae9478ffc5.png)
Then those would also introduce syndromes, I marked them with red dots (and I think I even forgot one at the bottom).
So does that mean that after a logical operation the logical qubit is no longer in the ground state?

With the introduced syndromes after a logical operation, does it still make sense to look at possible remaining syndromes as the first step? Wouldn't it make more sense to check the parity of x or z errors on the sides first?

**Comment by mats-granath** [comment]
No, those are not correct. The top one is an X_L operator but it does not have a syndrome. the last shaded semicircle stabilizer is an XX (vertex) stabilizer, so it commutes with the X_L operator. (At the end qubit it is the same X operator bot in the stabilizer as in the logical operator.)

The second string is not a logical operator, it has a syndrome, but on the two blank (Z-type, aka plaquette) stabilizers where there are three X operators in the string. An X string never gives rise to a syndrome on X-stabilizers. You could construct a meandering X_L from the top one by acting with Z-stabilizers, but it will not come out like that.

**Comment by mbecker12** [comment]
To add to the discussion, turns out I was confusing plaquettes and vertices

plaquettes = measuring parity of X errors = blank areas = consists of 4 Z operators (or 2 at the edge)
vertices = measuring parity of Z errors = shaded areas = consists of 4 X operators (or 2 at the edge)

Hence, my image above is wrong.
Also, there was a misunderstanding of how logical operators are constructed, which falsely led me to believe that the lower string of qubit errors is not a logical operation.
Thank you Mats for clearing that up!
