### ISSUE TITLE
Write Interface Class to generalize input to different NN architectures

### ISSUE THREAD

**Issue by mbecker12** [mbecker12/surface-rl-decoder#36]
Since we might want to try different architectures and different approaches in our networks to deal with the time component of the surface code, we want to create an interface module to help generalize to different approaches easily.

The idea is that the gym environment provides the output (state of the surface code) in the same way as usual.
This state then gets fed to this interface class.
The interface class can make adaptations to the state
E.g. might split it into a sequence of layers, or leave it in a stack as is.

This would allow to easily swap out different NN architectures which might expect different input shapes.

Note: the interface class will also have to handle batches of states.

**Comment by mbecker12** [comment]
![input_interface_class](https://user-images.githubusercontent.com/57626872/110468258-560e4880-80d8-11eb-84a4-c6ff516cacee.jpg)
Idea like this @falckk

**Comment by falckk** [comment]
interface is now part of the network, splitup happens first before they are propagated into the network

**Comment by falckk** [comment]
interface is now part of the network, splitup happens first before they are propagated into the network
