### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by falckk** [mbecker12/surface-rl-decoder#40]
Need to create a mapping from the output of the agent to the specific actions. Total number of actions should be 3d^2+1 actions.

**Comment by mbecker12** [comment]
The gym environment expects actions as tuples in the format (x-coordinate, y-coordinate, action-definition) or (Anything, x-coordinate, y-coordinate, action-definition) [the latter for compatibility reasons].
action-definition are defined as: 0 = Identity, 1 = Pauli-X, (2 = Pauli-Y), 3 = Pauli-Z and a terminal action, defined by the constant TERMINAL_ACTION in `surface_code_util.py`

**Comment by mbecker12** [comment]
Maybe look at code by Sweke or Gabriel&Adam, how they did the mapping since they already worked with deep q learning

**Comment by mbecker12** [comment]
function `action_to_q_value_index()` in `src.distributed.learner_util.py` on the branch `11/distributed-env` implements one way of this.
Doesn't support terminal action so far.

**Comment by mbecker12** [comment]
@falckk Added the functionality in `src.distributed.util.py`, functions `q_value_index_to_action()` and `action_to_q_value_index` on branch `11/distributed-env`
