### ISSUE TITLE
Rewrite agents to fit the new standard

### ISSUE THREAD

**Issue by falckk** [mbecker12/surface-rl-decoder#85]
Make sure the agents fit the new standards, also, change it so that batch is always first

**Comment by mbecker12** [comment]
For this task, I noticed something the other day:
In some runs, I'm logging the network parameters in the first and last layer, respectively.
For this, the order in which the layers are defined in the `__init__` function of each agent is important.
Before, the first defined layer was one that acted on the 'x' part of the split input. When I chose not to split the input, of course this layer did not learn, so logging it was unnecessary.

Therefore, it would be good if the first initialized layer is one that is always active, e.g. one that acts on `both`.
(Example on branch `86/check-actions`)

**Comment by mbecker12** [comment]
Check reshaping in 2dConv-LSTM model

**Comment by mbecker12** [comment]
Make number of layers configurable

**Comment by falckk** [comment]
New standard, take the toggle into consideration for the creation of the agent.
Fix module_list, it currently doesn't access the list and just goes through the iteration numbers.
Gated transformer for 2d_conv. Use the simple_2d as an example
Inherit from base agent everywhere 95/ppo

**Comment by mbecker12** [comment]
Also, clean up agents package: At the end, we only need one 2D Conv agent + one 3D Conv agent

**Comment by falckk** [comment]
Well, agents are done.
