### ISSUE TITLE
Create Neural Network Architecture

### ISSUE THREAD

**Issue by mbecker12** [mbecker12/surface-rl-decoder#9]
To be able to set up an agent, we need to define a suitable NN architecture.

Things to keep in mind here are:
- how do we process the syndrome stack?
- - extract feature vectors for each slice and concatenate them?
- - or extract one high-dimensional feature vector for the whole stack and further process that?

- what type of recurrent architecture (if any)?
- - transformer-like
- - RNN
- - LSTM

**Comment by falckk** [comment]
Only follow up tasks remains
